import PDFDocument from 'pdfkit';
import { db } from '@/db';
import {
  campaignInfluencers,
  campaigns,
  influencerProfiles,
  brandProfiles,
  users,
  bankDetails,
} from '@/db/schema';
import { eq, and, inArray } from 'drizzle-orm';
import { NotFoundError, BadRequestError } from '@/shared/errors';
import { sendEmail } from '@/shared/utils/email';

// ─── Mutiny company constants ─────────────────────────────────────────────────

const MUTINY = {
  name: 'Mutiny Talent Pvt. Ltd.',
  address: 'Plot No. 206, House No. 3, Kavurhills,\nHyderabad 500033, Telangana, India',
  gstin: '36AAHCT1219Q1ZX',
  email: 'support@mutinytalent.com',
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function fmtRupee(val: string | number | null | undefined): string {
  if (val == null) return '—';
  const n = Number(val);
  if (!Number.isFinite(n)) return '—';
  return `\u20B9${Math.abs(n).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function fmtDate(d?: Date | string | null): string {
  return new Date(d ?? Date.now()).toLocaleDateString('en-IN', {
    day: '2-digit', month: '2-digit', year: 'numeric',
  });
}

function makeInvoiceNumber(id: string, suffix = ''): string {
  return (id.replace(/-/g, '').slice(0, 10) + suffix).toUpperCase();
}

// ─── PDF layout helpers ───────────────────────────────────────────────────────

const M = 50;           // margin
const PW = 595 - M * 2; // usable page width (A4)
const ROW_H = 22;

const C = {
  black: '#111111',
  dark: '#333333',
  mid: '#666666',
  light: '#CCCCCC',
  faint: '#F7F7F7',
  tableBg: '#1A1A1A',
  tableText: '#FFFFFF',
};

const COL = {
  no: M,
  desc: M + 30,
  cost: M + PW - 140,
  total: M + PW - 65,
};

type Doc = InstanceType<typeof PDFDocument>;

function drawHRule(doc: Doc, y: number) {
  doc.moveTo(M, y).lineTo(M + PW, y).strokeColor(C.light).lineWidth(0.5).stroke();
}

function drawTableHeader(doc: Doc, y: number) {
  doc.rect(M, y, PW, ROW_H).fill(C.tableBg);
  doc.fillColor(C.tableText).fontSize(9).font('Helvetica-Bold');
  doc.text('No',          COL.no,    y + 7, { width: 25 });
  doc.text('Description', COL.desc,  y + 7, { width: COL.cost - COL.desc - 10 });
  doc.text('Cost',        COL.cost,  y + 7, { width: 70, align: 'right' });
  doc.text('Total',       COL.total, y + 7, { width: 65, align: 'right' });
  return y + ROW_H;
}

function drawTableRow(
  doc: Doc,
  y: number,
  no: string,
  desc: string,
  cost: string,
  total: string,
  stripe: boolean,
  italic = false,
) {
  if (stripe) doc.rect(M, y, PW, ROW_H).fill(C.faint);
  const font = italic ? 'Helvetica-Oblique' : 'Helvetica';
  doc.fillColor(C.black).fontSize(9).font(font);
  doc.text(no,   COL.no,    y + 7, { width: 25 });
  doc.text(desc, COL.desc,  y + 7, { width: COL.cost - COL.desc - 10 });
  doc.text(cost, COL.cost,  y + 7, { width: 70, align: 'right' });
  doc.text(total,COL.total, y + 7, { width: 65, align: 'right' });
  return y + ROW_H;
}

function drawGrandTotal(doc: Doc, y: number, amount: string) {
  doc.rect(M + PW - 200, y, 200, ROW_H + 2).fill(C.tableBg);
  doc.fillColor(C.tableText).fontSize(9).font('Helvetica-Bold')
    .text('GRAND TOTAL (INR)', M + PW - 200, y + 8, { width: 130, align: 'right' })
    .text(amount,              COL.total,     y + 8, { width: 65,  align: 'right' });
  return y + ROW_H + 2;
}

function drawFooter(doc: Doc) {
  const fy = doc.page.height - 55;
  drawHRule(doc, fy);
  doc.fillColor(C.mid).fontSize(8).font('Helvetica')
    .text(
      `This invoice is auto-generated by Mutiny Talent. For queries: ${MUTINY.email}`,
      M, fy + 10, { align: 'center', width: PW },
    )
    .text('© Mutiny Talent — Making creators unstoppable', M, fy + 24, { align: 'center', width: PW });
}

// ─── Brand invoice PDF ────────────────────────────────────────────────────────

interface BrandInvoiceData {
  invoiceNumber: string;
  date: Date;
  paymentType: 'advance' | 'final';
  brandName: string;
  brandEmail: string;
  brandCity?: string | null;
  campaignName: string;
  platform: string | null;
  // Per-CI breakdown
  influencerItems: Array<{ handle: string | null; roundBudget: number }>;
  // Payment-level totals (from campaign_payments record)
  platformFeePercent: number;
  platformFeeAmount: number;
  totalAmount: number;          // advance + fee (what brand paid this round)
  upcomingTotal: number | null; // null for final invoice
}

async function generateBrandInvoicePdf(data: BrandInvoiceData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: M });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const roundLabel = data.paymentType === 'advance' ? 'Advance (50%)' : 'Final (50%)';

    // Header
    doc.fontSize(28).font('Helvetica-Bold').fillColor(C.black).text('INVOICE', M, M);
    doc.fontSize(10).font('Helvetica').fillColor(C.dark)
      .text(`INVOICE NO: ${data.invoiceNumber}`, M + PW - 160, M,      { width: 160, align: 'right' })
      .text(`DATE: ${fmtDate(data.date)}`,        M + PW - 160, M + 16, { width: 160, align: 'right' })
      .text(`TYPE: ${roundLabel}`,                M + PW - 160, M + 32, { width: 160, align: 'right' });

    let y = M + 56;
    drawHRule(doc, y); y += 16;

    // Bill To (brand) + From (Mutiny)
    const half = PW / 2 - 10;
    doc.fontSize(9).font('Helvetica-Bold').fillColor(C.mid).text('Bill To:', M, y);
    doc.fontSize(11).font('Helvetica-Bold').fillColor(C.black).text(data.brandName, M, y + 14);
    doc.fontSize(9).font('Helvetica').fillColor(C.dark);
    let billY = y + 28;
    if (data.brandCity) { doc.text(data.brandCity, M, billY); billY += 13; }
    doc.text(data.brandEmail, M, billY);

    const fx = M + half + 20;
    doc.fontSize(9).font('Helvetica-Bold').fillColor(C.mid).text('From:', fx, y);
    doc.fontSize(11).font('Helvetica-Bold').fillColor(C.black).text(MUTINY.name, fx, y + 14);
    doc.fontSize(9).font('Helvetica').fillColor(C.dark)
      .text(MUTINY.address, fx, y + 28, { width: half })
      .text(`GSTIN: ${MUTINY.gstin}`, fx, y + 55);

    y += 82;
    drawHRule(doc, y); y += 10;
    doc.fontSize(9).font('Helvetica').fillColor(C.mid)
      .text(`Campaign: ${data.campaignName}${data.platform ? ` · ${data.platform}` : ''}`, M, y);
    y += 22;

    y = drawTableHeader(doc, y);

    let stripe = false;
    let rowNum = 1;

    // One row per influencer
    for (const item of data.influencerItems) {
      const label = `${item.handle ? `@${item.handle}` : 'Influencer'} – ${roundLabel}`;
      const amt = fmtRupee(item.roundBudget);
      y = drawTableRow(doc, y, String(rowNum++), label, amt, amt, stripe);
      stripe = !stripe;
    }

    // Platform fee row
    y = drawTableRow(
      doc, y,
      String(rowNum++),
      `Platform Service Fee (${data.platformFeePercent}%)`,
      fmtRupee(data.platformFeeAmount),
      fmtRupee(data.platformFeeAmount),
      stripe,
    );
    stripe = !stripe;

    // Upcoming final row (advance invoice only)
    if (data.upcomingTotal !== null) {
      y = drawTableRow(
        doc, y,
        String(rowNum++),
        'Final Payment – Upcoming (50%) *',
        fmtRupee(data.upcomingTotal),
        'Pending',
        stripe,
        true,
      );
    }

    y += 6;
    drawHRule(doc, y); y += 6;
    y = drawGrandTotal(doc, y, fmtRupee(data.totalAmount));
    y += 12;

    if (data.upcomingTotal !== null) {
      doc.fontSize(8).font('Helvetica-Oblique').fillColor(C.mid)
        .text('* Final payment amount is indicative and subject to influencer work approval.', M, y);
    }

    drawFooter(doc);
    doc.end();
  });
}

// ─── Influencer invoice PDF ───────────────────────────────────────────────────

interface InfluencerInvoiceData {
  invoiceNumber: string;
  date: Date;
  influencerName: string;
  influencerHandle: string | null;
  campaignName: string;
  platform: string | null;
  agreedBudget: number;
  platformFee: number;
  netPayout: number;
  bankHolderName: string | null;
  bankAccountNumber: string | null;
  bankName: string | null;
  ifscCode: string | null;
}

async function generateInfluencerInvoicePdf(data: InfluencerInvoiceData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: M });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.fontSize(28).font('Helvetica-Bold').fillColor(C.black).text('INVOICE', M, M);
    doc.fontSize(10).font('Helvetica').fillColor(C.dark)
      .text(`INVOICE NO: ${data.invoiceNumber}`, M + PW - 160, M,      { width: 160, align: 'right' })
      .text(`DATE: ${fmtDate(data.date)}`,        M + PW - 160, M + 16, { width: 160, align: 'right' });

    let y = M + 56;
    drawHRule(doc, y); y += 16;

    // Bill To (Mutiny) + From (Influencer)
    const half = PW / 2 - 10;
    doc.fontSize(9).font('Helvetica-Bold').fillColor(C.mid).text('Bill To:', M, y);
    doc.fontSize(11).font('Helvetica-Bold').fillColor(C.black).text(MUTINY.name, M, y + 14);
    doc.fontSize(9).font('Helvetica').fillColor(C.dark)
      .text(MUTINY.address, M, y + 28, { width: half })
      .text(`GSTIN: ${MUTINY.gstin}`, M, y + 55);

    const fx = M + half + 20;
    const displayName = data.influencerHandle
      ? data.influencerHandle.replace(/^@/, '').toUpperCase()
      : data.influencerName.toUpperCase();
    doc.fontSize(9).font('Helvetica-Bold').fillColor(C.mid).text('From:', fx, y);
    doc.fontSize(11).font('Helvetica-Bold').fillColor(C.black).text(displayName, fx, y + 14);
    doc.fontSize(9).font('Helvetica').fillColor(C.dark);
    let fromY = y + 28;
    if (data.influencerHandle) { doc.text(data.influencerName, fx, fromY); fromY += 13; }
    doc.text('Pan: —', fx, fromY);
    doc.text('Ph no.: —', fx, fromY + 13);

    y += 82;
    drawHRule(doc, y); y += 10;
    doc.fontSize(9).font('Helvetica').fillColor(C.mid)
      .text(`Campaign: ${data.campaignName}${data.platform ? ` · ${data.platform}` : ''}`, M, y);
    y += 22;

    y = drawTableHeader(doc, y);

    y = drawTableRow(doc, y, '1', `Content Creation – ${data.campaignName}`, fmtRupee(data.agreedBudget), fmtRupee(data.agreedBudget), false);
    y = drawTableRow(doc, y, '2', `Platform Fee Deduction (${Math.round((data.platformFee / data.agreedBudget) * 100)}%)`, `\u2013${fmtRupee(data.platformFee)}`, `\u2013${fmtRupee(data.platformFee)}`, true);

    y += 6;
    drawHRule(doc, y); y += 6;
    y = drawGrandTotal(doc, y, fmtRupee(data.netPayout));
    y += 24;

    // Bank details
    if (data.bankAccountNumber) {
      drawHRule(doc, y); y += 14;
      doc.fontSize(10).font('Helvetica-Bold').fillColor(C.black).text('Bank Details:', M, y);
      y += 18;

      const bankRows: Array<[string, string | null]> = [
        ['Bank Name',           data.bankName],
        ['Account Number',      data.bankAccountNumber],
        ['Account Holder Name', data.bankHolderName],
        ['IFSC Code',           data.ifscCode],
        ['Pan',                 null],
      ];

      for (const [label, val] of bankRows) {
        doc.fontSize(9).font('Helvetica-Bold').fillColor(C.dark)
          .text(`${label}: `, M, y, { continued: true })
          .font('Helvetica').fillColor(C.black)
          .text(val ?? '—');
        y += 14;
      }
    }

    // Authorized signature
    const sigY = doc.page.height - 100;
    doc.moveTo(M + PW - 140, sigY).lineTo(M + PW, sigY).strokeColor(C.black).lineWidth(0.5).stroke();
    doc.fontSize(9).font('Helvetica').fillColor(C.mid)
      .text('AUTHORIZED SIGNATURE', M + PW - 140, sigY + 7, { width: 140, align: 'center' });

    drawFooter(doc);
    doc.end();
  });
}

// ─── Email helper ─────────────────────────────────────────────────────────────

async function sendInvoiceEmail(
  to: string,
  name: string,
  campaignName: string,
  pdfBuffer: Buffer,
  invoiceNumber: string,
) {
  const subject = `Invoice #${invoiceNumber} — ${campaignName}`;
  const html = `
    <html><body style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;">
      <h2 style="color:#111111;">Campaign Invoice</h2>
      <p>Hi ${name},</p>
      <p>Please find the invoice for campaign <strong>${campaignName}</strong> attached.</p>
      <p>Invoice Number: <strong>#${invoiceNumber}</strong></p>
      <br/><p style="color:#666;">Thanks,<br/>Mutiny Talent Team</p>
    </body></html>
  `;
  await sendEmail({
    to,
    subject,
    html,
    attachments: [{ filename: `invoice-${invoiceNumber}.pdf`, content: pdfBuffer }],
  });
}

// ─── Brand invoice — sent after payment capture ───────────────────────────────

interface PaymentRecord {
  id: string;
  paymentType: string;
  round: number;
  influencerBudgetTotal: string;
  platformFeePercent: string;
  platformFeeAmount: string;
  totalAmount: string;
  capturedAt: Date | null;
}

/**
 * Called after advance or final payment is captured.
 * Sends a brand-facing invoice to the brand owner.
 * For advance invoices, it also shows the upcoming final payment amount.
 */
export async function sendBrandInvoiceAfterPayment(
  campaignId: string,
  ciIds: string[],
  payment: PaymentRecord,
): Promise<void> {
  if (!ciIds.length) return;

  const rows = await db
    .select({
      ci: {
        id: campaignInfluencers.id,
        agreedBudget: campaignInfluencers.agreedBudget,
      },
      influencer: { handle: influencerProfiles.handle },
      campaign: { name: campaigns.name, platform: campaigns.platform },
      brand: { brandName: brandProfiles.brandName, userId: brandProfiles.userId, city: brandProfiles.city },
    })
    .from(campaignInfluencers)
    .innerJoin(campaigns,          eq(campaigns.id, campaignInfluencers.campaignId))
    .innerJoin(brandProfiles,      eq(brandProfiles.id, campaigns.brandId))
    .innerJoin(influencerProfiles, eq(influencerProfiles.id, campaignInfluencers.influencerId))
    .where(
      and(
        eq(campaignInfluencers.campaignId, campaignId),
        inArray(campaignInfluencers.id, ciIds),
      )
    );

  if (!rows.length) return;

  const [brandUser] = await db
    .select({ name: users.name, email: users.email })
    .from(users)
    .where(eq(users.id, rows[0].brand.userId))
    .limit(1);

  if (!brandUser?.email) return;

  const paymentType = payment.paymentType as 'advance' | 'final';
  const platformFeePercent = Number(payment.platformFeePercent);
  const platformFeeAmount  = Number(payment.platformFeeAmount);
  const totalAmount        = Number(payment.totalAmount);
  const influencerBudgetTotal = Number(payment.influencerBudgetTotal);

  // Upcoming final payment = same budget total + same fee (indicative)
  const upcomingTotal = paymentType === 'advance'
    ? influencerBudgetTotal + platformFeeAmount
    : null;

  const influencerItems = rows.map((r) => ({
    handle: r.influencer.handle,
    roundBudget: Number(r.ci.agreedBudget ?? 0) * 0.5,
  }));

  const invNum = makeInvoiceNumber(payment.id, paymentType === 'advance' ? 'A' : 'F');
  const campaignName = rows[0].campaign.name;

  const pdfData: BrandInvoiceData = {
    invoiceNumber: invNum,
    date: payment.capturedAt ?? new Date(),
    paymentType,
    brandName: rows[0].brand.brandName,
    brandEmail: brandUser.email,
    brandCity: rows[0].brand.city,
    campaignName,
    platform: rows[0].campaign.platform,
    influencerItems,
    platformFeePercent,
    platformFeeAmount,
    totalAmount,
    upcomingTotal,
  };

  const pdf = await generateBrandInvoicePdf(pdfData);
  await sendInvoiceEmail(brandUser.email, brandUser.name, campaignName, pdf, invNum);
}

// ─── Influencer invoice — sent when CI status becomes completed ───────────────

/**
 * Called when a campaign influencer's status transitions to 'completed'
 * (work approved + final payment done, or product campaign work approved).
 * Sends a settlement invoice to the influencer with their net payout breakdown.
 */
export async function sendInfluencerInvoiceOnCompletion(ciId: string): Promise<void> {
  const [row] = await db
    .select({
      ci: {
        id: campaignInfluencers.id,
        agreedBudget: campaignInfluencers.agreedBudget,
        platformFee: campaignInfluencers.platformFee,
        completedAt: campaignInfluencers.completedAt,
      },
      campaign: { name: campaigns.name, platform: campaigns.platform },
      influencer: { handle: influencerProfiles.handle, userId: influencerProfiles.userId },
      influencerUser: { name: users.name, email: users.email },
    })
    .from(campaignInfluencers)
    .innerJoin(campaigns,          eq(campaigns.id, campaignInfluencers.campaignId))
    .innerJoin(influencerProfiles, eq(influencerProfiles.id, campaignInfluencers.influencerId))
    .innerJoin(users,              eq(users.id, influencerProfiles.userId))
    .where(eq(campaignInfluencers.id, ciId))
    .limit(1);

  if (!row || !row.influencerUser.email) return;

  const [bank] = await db
    .select()
    .from(bankDetails)
    .where(eq(bankDetails.userId, row.influencer.userId))
    .limit(1);

  const agreedBudget = Number(row.ci.agreedBudget ?? 0);
  const platformFee  = Number(row.ci.platformFee  ?? 0);
  const netPayout    = agreedBudget - platformFee;

  const invNum = makeInvoiceNumber(ciId, 'S'); // S = settlement
  const campaignName = row.campaign.name;

  const pdfData: InfluencerInvoiceData = {
    invoiceNumber: invNum,
    date: row.ci.completedAt ?? new Date(),
    influencerName: row.influencerUser.name,
    influencerHandle: row.influencer.handle,
    campaignName,
    platform: row.campaign.platform,
    agreedBudget,
    platformFee,
    netPayout,
    bankHolderName:    bank?.accountHolderName ?? null,
    bankAccountNumber: bank?.accountNumber     ?? null,
    bankName:          bank?.bankName          ?? null,
    ifscCode:          bank?.ifscCode          ?? null,
  };

  const pdf = await generateInfluencerInvoicePdf(pdfData);
  await sendInvoiceEmail(row.influencerUser.email, row.influencerUser.name, campaignName, pdf, invNum);
}

// ─── Manual trigger (influencer-initiated, existing endpoint) ─────────────────

export async function sendCampaignInvoice(campaignId: string, influencerUserId: string) {
  const [row] = await db
    .select({
      ci: {
        id: campaignInfluencers.id,
        status: campaignInfluencers.status,
        agreedBudget: campaignInfluencers.agreedBudget,
        platformFee: campaignInfluencers.platformFee,
        completedAt: campaignInfluencers.completedAt,
      },
      campaign: { name: campaigns.name, platform: campaigns.platform },
      brand: { brandName: brandProfiles.brandName, userId: brandProfiles.userId },
      influencer: { handle: influencerProfiles.handle, userId: influencerProfiles.userId },
      influencerUser: { name: users.name, email: users.email },
    })
    .from(campaignInfluencers)
    .innerJoin(campaigns,          eq(campaigns.id, campaignInfluencers.campaignId))
    .innerJoin(brandProfiles,      eq(brandProfiles.id, campaigns.brandId))
    .innerJoin(influencerProfiles, eq(influencerProfiles.id, campaignInfluencers.influencerId))
    .innerJoin(users,              eq(users.id, influencerProfiles.userId))
    .where(
      and(
        eq(campaignInfluencers.campaignId, campaignId),
        eq(influencerProfiles.userId, influencerUserId),
      )
    )
    .limit(1);

  if (!row) throw new NotFoundError('Campaign application not found');

  const allowedStatuses = [
    'accepted', 'payment_pending', 'paid',
    'script_pending', 'script_review',
    'work_pending', 'work_review',
    'completed', 'settled',
  ];
  if (!allowedStatuses.includes(row.ci.status)) {
    throw new BadRequestError('Invoice is only available after your application is accepted.');
  }

  const [bank] = await db
    .select()
    .from(bankDetails)
    .where(eq(bankDetails.userId, row.influencer.userId))
    .limit(1);

  const [brandUser] = await db
    .select({ name: users.name, email: users.email })
    .from(users)
    .where(eq(users.id, row.brand.userId))
    .limit(1);

  const agreedBudget = Number(row.ci.agreedBudget ?? 0);
  const platformFee  = Number(row.ci.platformFee  ?? 0);
  const netPayout    = agreedBudget - platformFee;
  const invNum       = makeInvoiceNumber(row.ci.id, 'S');
  const campaignName = row.campaign.name;

  const pdfData: InfluencerInvoiceData = {
    invoiceNumber: invNum,
    date: row.ci.completedAt ?? new Date(),
    influencerName: row.influencerUser.name,
    influencerHandle: row.influencer.handle,
    campaignName,
    platform: row.campaign.platform,
    agreedBudget,
    platformFee,
    netPayout,
    bankHolderName:    bank?.accountHolderName ?? null,
    bankAccountNumber: bank?.accountNumber     ?? null,
    bankName:          bank?.bankName          ?? null,
    ifscCode:          bank?.ifscCode          ?? null,
  };

  const pdf = await generateInfluencerInvoicePdf(pdfData);

  const emailedTo: string[] = [];
  if (row.influencerUser.email) {
    await sendInvoiceEmail(row.influencerUser.email, row.influencerUser.name, campaignName, pdf, invNum);
    emailedTo.push(row.influencerUser.email);
  }
  if (brandUser?.email) {
    await sendInvoiceEmail(brandUser.email, brandUser.name, campaignName, pdf, invNum);
    emailedTo.push(brandUser.email);
  }

  return { invoiceNumber: invNum, campaignName, emailedTo };
}
