// ─────────────────────────────────────────────────────────────
// Mock Data — Rich sample data for every module
// ─────────────────────────────────────────────────────────────

import type { CampaignInfluencer } from '@/shared/types/campaign';

export const MOCK_CAMPAIGNS = [
    {
        id: 'camp-001',
        name: 'Summer Glow Skincare Launch',
        type: 'influencer' as const,
        visibility: 'private' as const,
        objective: 'awareness',
        status: 'active' as const,
        budget: {
            mode: 'paid' as const,
            tierPricing: [
                { tier: 'micro' as const, amount: 8000 },
                { tier: 'mid' as const, amount: 15000 },
                { tier: 'macro' as const, amount: 30000 },
            ],
            total: 150000,
            platformFeePercent: 10,
        },
        location: 'Mumbai, India',
        niche: ['Beauty', 'Skincare'],
        creatorSize: 'micro' as const,
        creatorsInvited: 12,
        creatorsAccepted: 8,
        applicationsCount: 24,
        pendingScripts: 3,
        pendingSubmissions: 2,
        progress: 65,
        createdAt: '2026-02-10T10:00:00Z',
        deadline: '2026-03-15T23:59:59Z',
        thumbnail: undefined,
        proofOfWorkRequired: true,
        analytics: {
            totalLikes: 85400,
            totalComments: 1200,
            totalShares: 4500,
            totalReach: 1200000,
            engagementRate: 4.2
        },
        topPerformers: [
            { id: 'inf-001', name: 'Priya Sharma', handle: '@priyasharma', reach: 450000, engagement: 5.1 },
            { id: 'inf-005', name: 'Kavya Nair', handle: '@kavyafood', reach: 320000, engagement: 4.8 },
            { id: 'inf-006', name: 'Vikram Singh', handle: '@vikramfit', reach: 180000, engagement: 6.2 }
        ]
    },
    {
        id: 'camp-002',
        name: 'Viral Meme Challenge #BreakTheInternet',
        type: 'meme' as const,
        visibility: 'public' as const,
        objective: 'engagement',
        status: 'active' as const,
        budget: {
            mode: 'paid' as const,
            tierPricing: [
                { tier: 'nano' as const, amount: 3000 },
                { tier: 'micro' as const, amount: 5000 },
            ],
            total: 50000,
            platformFeePercent: 10,
        },
        location: 'Pan India',
        niche: ['Humor', 'Entertainment'],
        creatorSize: 'nano' as const,
        creatorsInvited: 20,
        creatorsAccepted: 15,
        applicationsCount: 45,
        pendingScripts: 0,
        pendingSubmissions: 5,
        progress: 80,
        createdAt: '2026-02-05T10:00:00Z',
        deadline: '2026-03-01T23:59:59Z',
        thumbnail: undefined,
        proofOfWorkRequired: false,
        analytics: {
            totalLikes: 250000,
            totalComments: 8500,
            totalShares: 45000,
            totalReach: 3500000,
            engagementRate: 7.5
        },
        topPerformers: [
            { id: 'inf-002', name: 'Arjun Kapoor', handle: '@arjunkmemes', reach: 1500000, engagement: 8.2 }
        ]
    },
    {
        id: 'camp-003',
        name: 'Twitter Spaces — FinTech Awareness',
        type: 'twitter' as const,
        visibility: 'private' as const,
        objective: 'awareness',
        status: 'draft' as const,
        budget: {
            mode: 'paid_product' as const,
            tierPricing: [
                { tier: 'mid' as const, amount: 8000 },
            ],
            total: 40000,
            platformFeePercent: 10,
        },
        location: 'Bangalore, India',
        niche: ['Finance', 'Technology'],
        creatorSize: 'mid' as const,
        creatorsInvited: 0,
        creatorsAccepted: 0,
        applicationsCount: 0,
        pendingScripts: 0,
        pendingSubmissions: 0,
        progress: 0,
        createdAt: '2026-02-20T10:00:00Z',
        deadline: '2026-04-01T23:59:59Z',
        thumbnail: undefined,
        proofOfWorkRequired: false,
    },
    {
        id: 'camp-004',
        name: 'UGC Product Unboxing — Tech Gadgets',
        type: 'ugc' as const,
        visibility: 'public' as const,
        objective: 'sales',
        status: 'active' as const,
        budget: {
            mode: 'product' as const,
            tierPricing: [],
            total: 0,
            platformFeePercent: 10,
        },
        location: 'Delhi NCR',
        niche: ['Technology', 'Gadgets'],
        creatorSize: 'nano' as const,
        creatorsInvited: 30,
        creatorsAccepted: 18,
        applicationsCount: 52,
        pendingScripts: 6,
        pendingSubmissions: 4,
        progress: 45,
        createdAt: '2026-02-15T10:00:00Z',
        deadline: '2026-03-20T23:59:59Z',
        thumbnail: undefined,
        proofOfWorkRequired: true,
        analytics: {
            totalLikes: 35400,
            totalComments: 850,
            totalShares: 900,
            totalReach: 850000,
            engagementRate: 5.1
        },
        topPerformers: [
            { id: 'inf-003', name: 'Sneha Reddy', handle: '@snehacodes', reach: 250000, engagement: 5.5 }
        ]
    },
    {
        id: 'camp-005',
        name: 'Food Review Series — Restaurant Chain',
        type: 'influencer' as const,
        visibility: 'public' as const,
        objective: 'sales',
        status: 'completed' as const,
        budget: {
            mode: 'paid' as const,
            tierPricing: [
                { tier: 'macro' as const, amount: 20000 },
            ],
            total: 200000,
            platformFeePercent: 10,
        },
        location: 'Hyderabad, India',
        niche: ['Food', 'Lifestyle'],
        creatorSize: 'macro' as const,
        creatorsInvited: 10,
        creatorsAccepted: 10,
        applicationsCount: 10,
        pendingScripts: 0,
        pendingSubmissions: 0,
        progress: 100,
        createdAt: '2026-01-10T10:00:00Z',
        deadline: '2026-02-10T23:59:59Z',
        thumbnail: undefined,
        proofOfWorkRequired: false,
        analytics: {
            totalLikes: 125000,
            totalComments: 4500,
            totalShares: 8500,
            totalReach: 2100000,
            engagementRate: 6.2
        },
        topPerformers: [
            { id: 'inf-005', name: 'Kavya Nair', handle: '@kavyafood', reach: 550000, engagement: 6.8 }
        ]
    },
];

export const MOCK_INFLUENCERS = [
    {
        id: 'inf-001',
        name: 'Priya Sharma',
        handle: '@priyasharma',
        avatar: undefined,
        bio: 'Beauty & skincare enthusiast 🌸 | 500K+ community | Brand collaborator | Mumbai based',
        location: 'Mumbai, India',
        platform: 'instagram' as const,
        followers: 520000,
        engagement: 4.2,
        avgViews: 85000,
        contentCount: 342,
        niche: ['Beauty', 'Skincare', 'Lifestyle'],
        creatorSize: 'mid' as const,
        languages: ['Hindi', 'English'],
        demographics: { age: { '18-24': 35, '25-34': 45, '35-44': 15, '45+': 5 }, gender: { female: 72, male: 28 }, topLocations: ['Mumbai', 'Delhi', 'Bangalore'] },
        socialAccounts: { instagram: { handle: '@priyasharma', followers: 520000 }, youtube: { handle: 'PriyaSharmaBlog', followers: 120000 }, twitter: null },
        pastCollaborations: 24,
        rating: 4.8,
    },
    {
        id: 'inf-002',
        name: 'Arjun Kapoor',
        handle: '@arjunkmemes',
        avatar: undefined,
        bio: 'Making India laugh one meme at a time 😂 | Meme lord | Content creator',
        location: 'Delhi, India',
        platform: 'instagram' as const,
        followers: 1200000,
        engagement: 6.8,
        avgViews: 350000,
        contentCount: 890,
        niche: ['Humor', 'Memes', 'Entertainment'],
        creatorSize: 'mega' as const,
        languages: ['Hindi', 'English'],
        demographics: { age: { '18-24': 55, '25-34': 30, '35-44': 10, '45+': 5 }, gender: { female: 40, male: 60 }, topLocations: ['Delhi', 'Mumbai', 'Pune'] },
        socialAccounts: { instagram: { handle: '@arjunkmemes', followers: 1200000 }, youtube: null, twitter: { handle: '@arjunmemes', followers: 85000 } },
        pastCollaborations: 56,
        rating: 4.9,
    },
    {
        id: 'inf-003',
        name: 'Sneha Reddy',
        handle: '@snehacodes',
        avatar: undefined,
        bio: 'Tech reviewer & gadget nerd 🔧 | YouTube 200K | Honest reviews only',
        location: 'Bangalore, India',
        platform: 'youtube' as const,
        followers: 200000,
        engagement: 5.1,
        avgViews: 45000,
        contentCount: 156,
        niche: ['Technology', 'Gadgets', 'Reviews'],
        creatorSize: 'mid' as const,
        languages: ['English', 'Telugu'],
        demographics: { age: { '18-24': 40, '25-34': 40, '35-44': 15, '45+': 5 }, gender: { female: 35, male: 65 }, topLocations: ['Bangalore', 'Hyderabad', 'Chennai'] },
        socialAccounts: { instagram: { handle: '@snehacodes', followers: 45000 }, youtube: { handle: 'SnehaCodes', followers: 200000 }, twitter: { handle: '@snehatech', followers: 32000 } },
        pastCollaborations: 18,
        rating: 4.6,
    },
    {
        id: 'inf-004',
        name: 'Rahul Deshpande',
        handle: '@rahulfinance',
        avatar: undefined,
        bio: 'Making finance fun 📊 | Twitter threads | Ex-banker turned creator',
        location: 'Pune, India',
        platform: 'twitter' as const,
        followers: 89000,
        engagement: 7.5,
        avgViews: 25000,
        contentCount: 510,
        niche: ['Finance', 'Investment', 'Education'],
        creatorSize: 'micro' as const,
        languages: ['English', 'Marathi'],
        demographics: { age: { '18-24': 20, '25-34': 50, '35-44': 25, '45+': 5 }, gender: { female: 30, male: 70 }, topLocations: ['Pune', 'Mumbai', 'Bangalore'] },
        socialAccounts: { instagram: null, youtube: null, twitter: { handle: '@rahulfinance', followers: 89000 } },
        pastCollaborations: 12,
        rating: 4.7,
    },
    {
        id: 'inf-005',
        name: 'Kavya Nair',
        handle: '@kavyafood',
        avatar: undefined,
        bio: 'Food blogger 🍕 | Discovering hidden gems | 80K community of foodies',
        location: 'Hyderabad, India',
        platform: 'instagram' as const,
        followers: 82000,
        engagement: 5.8,
        avgViews: 18000,
        contentCount: 234,
        niche: ['Food', 'Lifestyle', 'Travel'],
        creatorSize: 'micro' as const,
        languages: ['English', 'Malayalam', 'Hindi'],
        demographics: { age: { '18-24': 30, '25-34': 45, '35-44': 20, '45+': 5 }, gender: { female: 60, male: 40 }, topLocations: ['Hyderabad', 'Kochi', 'Chennai'] },
        socialAccounts: { instagram: { handle: '@kavyafood', followers: 82000 }, youtube: { handle: 'KavyaEats', followers: 15000 }, twitter: null },
        pastCollaborations: 32,
        rating: 4.5,
    },
    {
        id: 'inf-006',
        name: 'Vikram Singh',
        handle: '@vikramfit',
        avatar: undefined,
        bio: 'Fitness coach & UGC creator 💪 | Transform your body | Nano creator with high engagement',
        location: 'Jaipur, India',
        platform: 'instagram' as const,
        followers: 9500,
        engagement: 9.2,
        avgViews: 3500,
        contentCount: 87,
        niche: ['Fitness', 'Health', 'Wellness'],
        creatorSize: 'nano' as const,
        languages: ['Hindi', 'English'],
        demographics: { age: { '18-24': 45, '25-34': 40, '35-44': 10, '45+': 5 }, gender: { female: 25, male: 75 }, topLocations: ['Jaipur', 'Delhi', 'Mumbai'] },
        socialAccounts: { instagram: { handle: '@vikramfit', followers: 9500 }, youtube: null, twitter: null },
        pastCollaborations: 4,
        rating: 4.3,
    },
    {
        id: 'inf-007',
        name: 'Isha Gupta',
        handle: '@ishaglow',
        avatar: undefined,
        bio: 'Skincare scientist 🧪 | Honest ingredients analysis | Skincare over makeup',
        location: 'Mumbai, India',
        platform: 'instagram' as const,
        followers: 45000,
        engagement: 5.4,
        avgViews: 12000,
        contentCount: 189,
        niche: ['Skincare', 'Beauty'],
        creatorSize: 'micro' as const,
        languages: ['English', 'Hindi'],
        demographics: { age: { '18-24': 30, '25-34': 50, '35-44': 20 }, gender: { female: 85, male: 15 }, topLocations: ['Mumbai', 'Delhi'] },
        socialAccounts: { instagram: { handle: '@ishaglow', followers: 45000 }, youtube: null, twitter: null },
        pastCollaborations: 15,
        rating: 4.7,
    },
    {
        id: 'inf-008',
        name: 'Ananya Roy',
        handle: '@anayaroybeauty',
        avatar: undefined,
        bio: 'Professional Makeup Artist 💄 | Bridal Expert | Beauty Tips',
        location: 'Kolkata, India',
        platform: 'instagram' as const,
        followers: 120000,
        engagement: 4.9,
        avgViews: 45000,
        contentCount: 450,
        niche: ['Beauty', 'Skincare'],
        creatorSize: 'mid' as const,
        languages: ['Bengali', 'English', 'Hindi'],
        demographics: { age: { '18-24': 25, '25-34': 55, '35-44': 20 }, gender: { female: 90, male: 10 }, topLocations: ['Kolkata', 'Delhi'] },
        socialAccounts: { instagram: { handle: '@anayaroybeauty', followers: 120000 }, youtube: null, twitter: null },
        pastCollaborations: 40,
        rating: 4.9,
    },
    {
        id: 'inf-009',
        name: 'Zoya Khan',
        handle: '@zoyaskin',
        avatar: undefined,
        bio: 'Eco-conscious beauty 🌿 | Vegan skincare | Natural living',
        location: 'Hyderabad, India',
        platform: 'instagram' as const,
        followers: 32000,
        engagement: 6.1,
        avgViews: 8000,
        contentCount: 120,
        niche: ['Skincare', 'Lifestyle'],
        creatorSize: 'micro' as const,
        languages: ['Urdu', 'English', 'Telugu'],
        demographics: { age: { '18-24': 40, '25-34': 40, '35-44': 20 }, gender: { female: 88, male: 12 }, topLocations: ['Hyderabad', 'Bangalore'] },
        socialAccounts: { instagram: { handle: '@zoyaskin', followers: 32000 }, youtube: null, twitter: null },
        pastCollaborations: 8,
        rating: 4.4,
    },
    {
        id: 'inf-010',
        name: 'Meera Iyer',
        handle: '@meerasbeauty',
        avatar: undefined,
        bio: 'Ayurvedic Skincare Secrets 🧘‍♀️ | Traditional meets Modern',
        location: 'Chennai, India',
        platform: 'instagram' as const,
        followers: 75000,
        engagement: 5.2,
        avgViews: 20000,
        contentCount: 210,
        niche: ['Skincare', 'Wellness'],
        creatorSize: 'micro' as const,
        languages: ['Tamil', 'English', 'Hindi'],
        demographics: { age: { '18-24': 20, '25-34': 60, '35-44': 20 }, gender: { female: 82, male: 18 }, topLocations: ['Chennai', 'Bangalore'] },
        socialAccounts: { instagram: { handle: '@meerasbeauty', followers: 75000 }, youtube: null, twitter: null },
        pastCollaborations: 18,
        rating: 4.6,
    },
    {
        id: 'inf-011',
        name: 'Rohan Mehta',
        handle: '@rohan_grooming',
        avatar: undefined,
        bio: 'Mens Grooming & Lifestyle 🧔 | Selfcare for men',
        location: 'Delhi, India',
        platform: 'instagram' as const,
        followers: 55000,
        engagement: 4.5,
        avgViews: 15000,
        contentCount: 175,
        niche: ['Beauty', 'Lifestyle'],
        creatorSize: 'micro' as const,
        languages: ['Hindi', 'English'],
        demographics: { age: { '18-24': 50, '25-34': 40, '35-44': 10 }, gender: { female: 15, male: 85 }, topLocations: ['Delhi', 'Chandigarh'] },
        socialAccounts: { instagram: { handle: '@rohan_grooming', followers: 55000 }, youtube: null, twitter: null },
        pastCollaborations: 12,
        rating: 4.5,
    },
    {
        id: 'inf-012',
        name: 'Sanya Malhotra',
        handle: '@sanyaskincare',
        avatar: undefined,
        bio: 'Clear skin journey ✨ | Acne positivity | Skincare routine daily',
        location: 'Pune, India',
        platform: 'instagram' as const,
        followers: 18000,
        engagement: 7.2,
        avgViews: 5000,
        contentCount: 95,
        niche: ['Skincare', 'Beauty'],
        creatorSize: 'nano' as const,
        languages: ['Marathi', 'English', 'Hindi'],
        demographics: { age: { '18-24': 65, '25-34': 25, '35-44': 10 }, gender: { female: 95, male: 5 }, topLocations: ['Pune', 'Mumbai'] },
        socialAccounts: { instagram: { handle: '@sanyaskincare', followers: 18000 }, youtube: null, twitter: null },
        pastCollaborations: 5,
        rating: 4.2,
    },
    {
        id: 'inf-013',
        name: 'Aavani Shah',
        handle: '@aavanibeauty',
        avatar: undefined,
        bio: 'Luxury Beauty Reviewer 💎 | High-end skincare analysis',
        location: 'Ahmedabad, India',
        platform: 'instagram' as const,
        followers: 92000,
        engagement: 4.8,
        avgViews: 25000,
        contentCount: 320,
        niche: ['Beauty', 'Skincare'],
        creatorSize: 'micro' as const,
        languages: ['Gujarati', 'English', 'Hindi'],
        demographics: { age: { '18-24': 15, '25-34': 65, '35-44': 20 }, gender: { female: 80, male: 20 }, topLocations: ['Ahmedabad', 'Mumbai'] },
        socialAccounts: { instagram: { handle: '@aavanibeauty', followers: 92000 }, youtube: null, twitter: null },
        pastCollaborations: 22,
        rating: 4.8,
    },
    {
        id: 'inf-014',
        name: 'Tanya Verma',
        handle: '@tanya_glowup',
        avatar: undefined,
        bio: 'Budget beauty hacks 💸 | Drugstore skincare expert',
        location: 'Lucknow, India',
        platform: 'instagram' as const,
        followers: 110000,
        engagement: 5.9,
        avgViews: 35000,
        contentCount: 280,
        niche: ['Beauty', 'Skincare'],
        creatorSize: 'mid' as const,
        languages: ['Hindi', 'English'],
        demographics: { age: { '18-24': 45, '25-34': 45, '35-44': 10 }, gender: { female: 85, male: 15 }, topLocations: ['Lucknow', 'Delhi'] },
        socialAccounts: { instagram: { handle: '@tanya_glowup', followers: 110000 }, youtube: null, twitter: null },
        pastCollaborations: 35,
        rating: 4.7,
    },
    {
        id: 'inf-015',
        name: 'Kabir Das',
        handle: '@kabir_grooming',
        avatar: undefined,
        bio: 'Grooming for the modern man 🧔 | Beard care & skincare',
        location: 'Bangalore, India',
        platform: 'instagram' as const,
        followers: 25000,
        engagement: 6.5,
        avgViews: 7000,
        contentCount: 110,
        niche: ['Beauty', 'Lifestyle'],
        creatorSize: 'micro' as const,
        languages: ['English', 'Kannada', 'Hindi'],
        demographics: { age: { '18-24': 30, '25-34': 50, '35-44': 20 }, gender: { female: 5, male: 95 }, topLocations: ['Bangalore', 'Mysore'] },
        socialAccounts: { instagram: { handle: '@kabir_grooming', followers: 25000 }, youtube: null, twitter: null },
        pastCollaborations: 7,
        rating: 4.4,
    },
    {
        id: 'inf-016',
        name: 'Riya Sen',
        handle: '@riyaskincare',
        avatar: undefined,
        bio: 'Dermatologist recommended skincare 🏥 | Clinical beauty reviews',
        location: 'Mumbai, India',
        platform: 'instagram' as const,
        followers: 150000,
        engagement: 4.1,
        avgViews: 40000,
        contentCount: 410,
        niche: ['Skincare', 'Health'],
        creatorSize: 'mid' as const,
        languages: ['English', 'Hindi'],
        demographics: { age: { '18-24': 20, '25-34': 60, '35-44': 20 }, gender: { female: 75, male: 25 }, topLocations: ['Mumbai', 'Delhi'] },
        socialAccounts: { instagram: { handle: '@riyaskincare', followers: 150000 }, youtube: null, twitter: null },
        pastCollaborations: 45,
        rating: 4.8,
    },
    { id: 'inf-017', name: 'Zaid Ali', handle: '@zaidfitness', bio: 'Transformation expert | 1-on-1 coaching', location: 'Dubai, UAE', platform: 'instagram', followers: 85000, engagement: 5.2, creatorSize: 'micro', niche: ['Fitness'], socialAccounts: { instagram: { handle: '@zaidfitness', followers: 85000 }, youtube: null, twitter: null }, pastCollaborations: 12, rating: 4.5 },
    { id: 'inf-018', name: 'Sara Khan', handle: '@sara_cooks', bio: 'Quick 15-min recipes | Foodie for life', location: 'London, UK', platform: 'instagram', followers: 210000, engagement: 4.8, creatorSize: 'mid', niche: ['Food'], socialAccounts: { instagram: { handle: '@sara_cooks', followers: 210000 }, youtube: null, twitter: null }, pastCollaborations: 25, rating: 4.7 },
    { id: 'inf-019', name: 'Kenji Sato', handle: '@kenji_tech', bio: 'Gadget unboxings | Future of AI', location: 'Tokyo, Japan', platform: 'youtube', followers: 1200000, engagement: 3.5, creatorSize: 'macro', niche: ['Tech'], socialAccounts: { instagram: null, youtube: { handle: 'Kenji Tech', followers: 1200000 }, twitter: null }, pastCollaborations: 55, rating: 4.9 },
    { id: 'inf-020', name: 'Elena Rossi', handle: '@elena_fashion', bio: 'Milan street style | Luxury fashion', location: 'Milan, Italy', platform: 'instagram', followers: 450000, engagement: 4.2, creatorSize: 'macro', niche: ['Fashion'], socialAccounts: { instagram: { handle: '@elena_fashion', followers: 450000 }, youtube: null, twitter: null }, pastCollaborations: 40, rating: 4.8 },
    { id: 'inf-021', name: 'David Chen', handle: '@dchen_travel', bio: 'Exploring hidden gems | Travel photography', location: 'Singapore', platform: 'instagram', followers: 65000, engagement: 6.1, creatorSize: 'micro', niche: ['Travel'], socialAccounts: { instagram: { handle: '@dchen_travel', followers: 65000 }, youtube: null, twitter: null }, pastCollaborations: 18, rating: 4.6 },
    { id: 'inf-022', name: 'Marta Silva', handle: '@marta_yoga', bio: 'Yoga for beginners | Mindfulness & peace', location: 'Lisbon, Portugal', platform: 'instagram', followers: 32000, engagement: 7.5, creatorSize: 'micro', niche: ['Wellness'], socialAccounts: { instagram: { handle: '@marta_yoga', followers: 32000 }, youtube: null, twitter: null }, pastCollaborations: 9, rating: 4.4 },
    { id: 'inf-023', name: 'Alex Thompson', handle: '@alext_gaming', bio: 'Daily streams | RPG enthusiast', location: 'Austin, USA', platform: 'youtube', followers: 850000, engagement: 3.9, creatorSize: 'mid', niche: ['Gaming'], socialAccounts: { instagram: null, youtube: { handle: 'AlexT Gaming', followers: 850000 }, twitter: null }, pastCollaborations: 30, rating: 4.7 },
    { id: 'inf-024', name: 'Nora Al-Farsi', handle: '@nora_beauty', bio: 'Middle Eastern beauty secrets | Skincare', location: 'Riyadh, Saudi Arabia', platform: 'instagram', followers: 150000, engagement: 5.8, creatorSize: 'mid', niche: ['Beauty'], socialAccounts: { instagram: { handle: '@nora_beauty', followers: 150000 }, youtube: null, twitter: null }, pastCollaborations: 22, rating: 4.8 },
    { id: 'inf-025', name: 'Liam Wilson', handle: '@liam_beats', bio: 'Music producer | Weekly beat drops', location: 'Berlin, Germany', platform: 'instagram', followers: 42000, engagement: 5.5, creatorSize: 'micro', niche: ['Music'], socialAccounts: { instagram: { handle: '@liam_beats', followers: 42000 }, youtube: null, twitter: null }, pastCollaborations: 15, rating: 4.5 },
    { id: 'inf-026', name: 'Chloe Dubois', handle: '@chloe_art', bio: 'Digital illustrator | Commissions open', location: 'Paris, France', platform: 'instagram', followers: 180000, engagement: 4.7, creatorSize: 'mid', niche: ['Art'], socialAccounts: { instagram: { handle: '@chloe_art', followers: 180000 }, youtube: null, twitter: null }, pastCollaborations: 28, rating: 4.6 },
    { id: 'inf-027', name: 'Hassan Raza', handle: '@hassan_vlogs', bio: 'Life in Karachi | Travel & street food', location: 'Karachi, Pakistan', platform: 'youtube', followers: 550000, engagement: 4.1, creatorSize: 'mid', niche: ['Travel'], socialAccounts: { instagram: null, youtube: { handle: 'Hassan Vlogs', followers: 550000 }, twitter: null }, pastCollaborations: 35, rating: 4.7 },
    { id: 'inf-028', name: 'Yuki Tanaka', handle: '@yuki_fit', bio: 'Home workouts | Nutrition for busy people', location: 'Osaka, Japan', platform: 'instagram', followers: 92000, engagement: 5.3, creatorSize: 'micro', niche: ['Fitness'], socialAccounts: { instagram: { handle: '@yuki_fit', followers: 92000 }, youtube: null, twitter: null }, pastCollaborations: 12, rating: 4.4 },
    { id: 'inf-029', name: 'Sofia Garcia', handle: '@sofia_decor', bio: 'DIY home styling | Minimalist living', location: 'Madrid, Spain', platform: 'instagram', followers: 125000, engagement: 4.9, creatorSize: 'mid', niche: ['Lifestyle'], socialAccounts: { instagram: { handle: '@sofia_decor', followers: 125000 }, youtube: null, twitter: null }, pastCollaborations: 20, rating: 4.8 },
    { id: 'inf-030', name: 'Ahmed Mansour', handle: '@ahmed_tech', bio: 'Tech reviews in Arabic | Smartphone expert', location: 'Cairo, Egypt', platform: 'youtube', followers: 2200000, engagement: 3.2, creatorSize: 'macro', niche: ['Tech'], socialAccounts: { instagram: null, youtube: { handle: 'Ahmed Tech', followers: 2200000 }, twitter: null }, pastCollaborations: 60, rating: 4.9 },
    { id: 'inf-031', name: 'Olga Petrova', handle: '@olga_ballet', bio: 'Russian ballet life | Pro dancer tips', location: 'St. Petersburg, Russia', platform: 'instagram', followers: 78000, engagement: 6.4, creatorSize: 'micro', niche: ['Art'], socialAccounts: { instagram: { handle: '@olga_ballet', followers: 78000 }, youtube: null, twitter: null }, pastCollaborations: 14, rating: 4.7 },
    { id: 'inf-032', name: 'James Kim', handle: '@james_coding', bio: 'Fullstack dev logs | Learn to code daily', location: 'Seoul, South Korea', platform: 'youtube', followers: 450000, engagement: 5.1, creatorSize: 'mid', niche: ['Education'], socialAccounts: { instagram: null, youtube: { handle: 'James Coding', followers: 450000 }, twitter: null }, pastCollaborations: 25, rating: 4.8 },
    { id: 'inf-033', name: 'Fatima Zahra', handle: '@fatima_modest', bio: 'Modest fashion | Hijab styling tips', location: 'Casablanca, Morocco', platform: 'instagram', followers: 310000, engagement: 4.6, creatorSize: 'mid', niche: ['Fashion'], socialAccounts: { instagram: { handle: '@fatima_modest', followers: 310000 }, youtube: null, twitter: null }, pastCollaborations: 32, rating: 4.6 },
    { id: 'inf-034', name: 'Lucas Meyer', handle: '@lucas_outdoor', bio: 'Camping & hiking gear reviews', location: 'Munich, Germany', platform: 'instagram', followers: 52000, engagement: 5.7, creatorSize: 'micro', niche: ['Travel'], socialAccounts: { instagram: { handle: '@lucas_outdoor', followers: 52000 }, youtube: null, twitter: null }, pastCollaborations: 16, rating: 4.5 },
    { id: 'inf-035', name: 'Aisha Bello', handle: '@aisha_styles', bio: 'Nollywood red carpet designer', location: 'Lagos, Nigeria', platform: 'instagram', followers: 185000, engagement: 4.3, creatorSize: 'mid', niche: ['Fashion'], socialAccounts: { instagram: { handle: '@aisha_styles', followers: 185000 }, youtube: null, twitter: null }, pastCollaborations: 24, rating: 4.7 },
    { id: 'inf-036', name: 'Igor Sokolov', handle: '@igor_chess', bio: 'Grandmaster analysis | Chess tips', location: 'Moscow, Russia', platform: 'youtube', followers: 120000, engagement: 7.2, creatorSize: 'micro', niche: ['Entertainment'], socialAccounts: { instagram: null, youtube: { handle: 'Igor Chess', followers: 120000 }, twitter: null }, pastCollaborations: 8, rating: 4.8 },
    { id: 'inf-037', name: 'Isabella Lima', handle: '@bella_bela', bio: 'Rio lifestyle | Beach & fitness lover', location: 'Rio de Janeiro, Brazil', platform: 'instagram', followers: 240000, engagement: 5.1, creatorSize: 'mid', niche: ['Lifestyle'], socialAccounts: { instagram: { handle: '@bella_bela', followers: 240000 }, youtube: null, twitter: null }, pastCollaborations: 21, rating: 4.6 },
    { id: 'inf-038', name: 'Wei Zhang', handle: '@wei_photo', bio: 'Cinematic street photography', location: 'Shanghai, China', platform: 'instagram', followers: 610000, engagement: 4.4, creatorSize: 'macro', niche: ['Art'], socialAccounts: { instagram: { handle: '@wei_photo', followers: 610000 }, youtube: null, twitter: null }, pastCollaborations: 45, rating: 4.9 },
    { id: 'inf-039', name: 'Aarav Kumar', handle: '@aarav_tech', bio: 'Building startups | Product management', location: 'Bangalore, India', platform: 'twitter', followers: 45000, engagement: 8.2, creatorSize: 'micro', niche: ['Education'], socialAccounts: { instagram: null, youtube: null, twitter: { handle: '@aarav_tech', followers: 45000 } }, pastCollaborations: 10, rating: 4.7 },
    { id: 'inf-040', name: 'Emilia Clarke', handle: '@emilia_reads', bio: 'Book reviews | Fantasy & Sci-Fi lover', location: 'London, UK', platform: 'instagram', followers: 110000, engagement: 5.9, creatorSize: 'mid', niche: ['Entertainment'], socialAccounts: { instagram: { handle: '@emilia_reads', followers: 110000 }, youtube: null, twitter: null }, pastCollaborations: 19, rating: 4.8 },
    { id: 'inf-041', name: 'Omar Farooq', handle: '@omar_eats', bio: 'Food adventures across the GCC', location: 'Doha, Qatar', platform: 'instagram', followers: 195000, engagement: 4.7, creatorSize: 'mid', niche: ['Food'], socialAccounts: { instagram: { handle: '@omar_eats', followers: 195000 }, youtube: null, twitter: null }, pastCollaborations: 26, rating: 4.6 },
    { id: 'inf-042', name: 'Tina Tran', handle: '@tina_makeup', bio: 'Easy Asian makeup tutorials', location: 'Ho Chi Minh City, Vietnam', platform: 'instagram', followers: 320000, engagement: 5.0, creatorSize: 'mid', niche: ['Beauty'], socialAccounts: { instagram: { handle: '@tina_makeup', followers: 320000 }, youtube: null, twitter: null }, pastCollaborations: 30, rating: 4.9 },
    { id: 'inf-043', name: 'Ben Walker', handle: '@ben_car_vlogs', bio: 'Car restoration & weekly reviews', location: 'Detroit, USA', platform: 'youtube', followers: 950000, engagement: 3.8, creatorSize: 'mid', niche: ['Lifestyle'], socialAccounts: { instagram: null, youtube: { handle: 'Ben Car Vlogs', followers: 950000 }, twitter: null }, pastCollaborations: 38, rating: 4.7 },
    { id: 'inf-044', name: 'Leila Sadat', handle: '@leila_skin', bio: 'Dermatologist verified skincare', location: 'Tehran, Iran', platform: 'instagram', followers: 85000, engagement: 5.4, creatorSize: 'micro', niche: ['Skincare'], socialAccounts: { instagram: { handle: '@leila_skin', followers: 85000 }, youtube: null, twitter: null }, pastCollaborations: 14, rating: 4.8 },
    { id: 'inf-045', name: 'Rafael Gomez', handle: '@rafa_skate', bio: 'Skateboarding tricks & pro tips', location: 'Barcelona, Spain', platform: 'instagram', followers: 140000, engagement: 6.7, creatorSize: 'mid', niche: ['Sports'], socialAccounts: { instagram: { handle: '@rafa_skate', followers: 140000 }, youtube: null, twitter: null }, pastCollaborations: 22, rating: 4.6 },
    { id: 'inf-046', name: 'Kim Ji-won', handle: '@jiwon_fit', bio: 'Pilates instructor | Wellness blogger', location: 'Seoul, South Korea', platform: 'instagram', followers: 205000, engagement: 4.9, creatorSize: 'mid', niche: ['Fitness'], socialAccounts: { instagram: { handle: '@jiwon_fit', followers: 205000 }, youtube: null, twitter: null }, pastCollaborations: 18, rating: 4.7 },
    { id: 'inf-047', name: 'Samuel Jackson', handle: '@sam_crypto', bio: 'Web3 & crypto analysis daily', location: 'New York, USA', platform: 'twitter', followers: 110000, engagement: 7.1, creatorSize: 'mid', niche: ['Tech'], socialAccounts: { instagram: null, youtube: null, twitter: { handle: '@sam_crypto', followers: 110000 } }, pastCollaborations: 15, rating: 4.5 },
    { id: 'inf-048', name: 'Noor Jafri', handle: '@noor_design', bio: 'Architectural digest & home tours', location: 'Lahore, Pakistan', platform: 'instagram', followers: 72000, engagement: 5.2, creatorSize: 'micro', niche: ['Lifestyle'], socialAccounts: { instagram: { handle: '@noor_design', followers: 72000 }, youtube: null, twitter: null }, pastCollaborations: 11, rating: 4.4 },
    { id: 'inf-049', name: 'Hans Muller', handle: '@hans_mountain', bio: 'Alpine climbing & breathtaking views', location: 'Zurich, Switzerland', platform: 'instagram', followers: 125000, engagement: 6.3, creatorSize: 'mid', niche: ['Travel'], socialAccounts: { instagram: { handle: '@hans_mountain', followers: 125000 }, youtube: null, twitter: null }, pastCollaborations: 20, rating: 4.9 },
    { id: 'inf-050', name: 'Yasmine Ali', handle: '@yasmine_bakes', bio: 'Middle Eastern desserts made easy', location: 'Amman, Jordan', platform: 'instagram', followers: 165000, engagement: 5.5, creatorSize: 'mid', niche: ['Food'], socialAccounts: { instagram: { handle: '@yasmine_bakes', followers: 165000 }, youtube: null, twitter: null }, pastCollaborations: 25, rating: 4.7 },
    { id: 'inf-051', name: 'Tom Jones', handle: '@tom_adventure', bio: 'Solo backpacking across the world', location: 'Sydney, Australia', platform: 'youtube', followers: 650000, engagement: 4.2, creatorSize: 'mid', niche: ['Travel'], socialAccounts: { instagram: null, youtube: { handle: 'Tom Adventure', followers: 650000 }, twitter: null }, pastCollaborations: 30, rating: 4.8 },
    { id: 'inf-052', name: 'Lia Martinez', handle: '@lia_art', bio: 'Oil painting tutorials & tips', location: 'Mexico City, Mexico', platform: 'instagram', followers: 98000, engagement: 6.8, creatorSize: 'micro', niche: ['Art'], socialAccounts: { instagram: { handle: '@lia_art', followers: 98000 }, youtube: null, twitter: null }, pastCollaborations: 12, rating: 4.6 },
    { id: 'inf-053', name: 'Artyom Volkov', handle: '@artyom_tech', bio: 'Hardware hacking & PC building', location: 'Kiev, Ukraine', platform: 'youtube', followers: 320000, engagement: 5.9, creatorSize: 'mid', niche: ['Tech'], socialAccounts: { instagram: null, youtube: { handle: 'Artyom Tech', followers: 320000 }, twitter: null }, pastCollaborations: 24, rating: 4.9 },
    { id: 'inf-054', name: 'Elena Mendez', handle: '@elena_yoga', bio: 'Prenatal yoga & holistic health', location: 'Buenos Aires, Argentina', platform: 'instagram', followers: 54000, engagement: 5.6, creatorSize: 'micro', niche: ['Wellness'], socialAccounts: { instagram: { handle: '@elena_yoga', followers: 54000 }, youtube: null, twitter: null }, pastCollaborations: 13, rating: 4.5 },
    { id: 'inf-055', name: 'Vikram Joshi', handle: '@vikram_history', bio: 'Untold stories from Indian history', location: 'Pune, India', platform: 'youtube', followers: 480000, engagement: 6.1, creatorSize: 'mid', niche: ['Education'], socialAccounts: { instagram: null, youtube: { handle: 'Vikram History', followers: 480000 }, twitter: null }, pastCollaborations: 28, rating: 4.8 },
    { id: 'inf-056', name: 'Sara Lee', handle: '@sara_makeup', bio: 'K-beauty for all skin types', location: 'Incheon, South Korea', platform: 'instagram', followers: 215000, engagement: 4.3, creatorSize: 'mid', niche: ['Beauty'], socialAccounts: { instagram: { handle: '@sara_makeup', followers: 215000 }, youtube: null, twitter: null }, pastCollaborations: 19, rating: 4.4 },
    { id: 'inf-057', name: 'Dmitry Pavlov', handle: '@dmitry_chess', bio: 'Speed chess & strategy review', location: 'Nizhny Novgorod, Russia', platform: 'twitch', followers: 45000, engagement: 9.1, creatorSize: 'micro', niche: ['Entertainment'], socialAccounts: { instagram: null, youtube: null, twitter: null }, pastCollaborations: 5, rating: 4.7 },
    { id: 'inf-058', name: 'Amelie Laurent', handle: '@amelie_decor', bio: 'Parisian chic interior design', location: 'Lyon, France', platform: 'instagram', followers: 310000, engagement: 5.0, creatorSize: 'mid', niche: ['Lifestyle'], socialAccounts: { instagram: { handle: '@amelie_decor', followers: 310000 }, youtube: null, twitter: null }, pastCollaborations: 27, rating: 4.8 },
    { id: 'inf-059', name: 'Rajesh Khanna', handle: '@rajesh_stock', bio: 'Indian stock market analysis', location: 'Mumbai, India', platform: 'youtube', followers: 1200000, engagement: 3.4, creatorSize: 'macro', niche: ['Education'], socialAccounts: { instagram: null, youtube: { handle: 'Rajesh Stock', followers: 1200000 }, twitter: null }, pastCollaborations: 50, rating: 4.9 },
    { id: 'inf-060', name: 'Sofia Rodriguez', handle: '@sofia_travel', bio: 'Backpacker logs | Central America', location: 'San Jose, Costa Rica', platform: 'instagram', followers: 85000, engagement: 5.8, creatorSize: 'micro', niche: ['Travel'], socialAccounts: { instagram: { handle: '@sofia_travel', followers: 85000 }, youtube: null, twitter: null }, pastCollaborations: 15, rating: 4.6 },
    { id: 'inf-061', name: 'Kenji Suzuki', handle: '@kenji_ramen', bio: 'Hunt for the best ramen in Tokyo', location: 'Yokohama, Japan', platform: 'instagram', followers: 145000, engagement: 4.7, creatorSize: 'mid', niche: ['Food'], socialAccounts: { instagram: { handle: '@kenji_ramen', followers: 145000 }, youtube: null, twitter: null }, pastCollaborations: 22, rating: 4.7 },
    { id: 'inf-062', name: 'Fatima Ahmed', handle: '@fatima_vlogs', bio: 'Daily life in London | Somali creator', location: 'London, UK', platform: 'youtube', followers: 310000, engagement: 5.3, creatorSize: 'mid', niche: ['Lifestyle'], socialAccounts: { instagram: null, youtube: { handle: 'Fatima Vlogs', followers: 310000 }, twitter: null }, pastCollaborations: 30, rating: 4.8 },
    { id: 'inf-063', name: 'Liam Davies', handle: '@liam_music', bio: 'Acoustic covers & original songs', location: 'Manchester, UK', platform: 'instagram', followers: 62000, engagement: 6.9, creatorSize: 'micro', niche: ['Entertainment'], socialAccounts: { instagram: { handle: '@liam_music', followers: 62000 }, youtube: null, twitter: null }, pastCollaborations: 11, rating: 4.5 },
    { id: 'inf-064', name: 'Chloe Kim', handle: '@chloe_beauty', bio: 'Organic skincare & luxury makeup', location: 'Seattle, USA', platform: 'instagram', followers: 195000, engagement: 4.5, creatorSize: 'mid', niche: ['Beauty'], socialAccounts: { instagram: { handle: '@chloe_beauty', followers: 195000 }, youtube: null, twitter: null }, pastCollaborations: 24, rating: 4.7 },
    { id: 'inf-065', name: 'Marta Rossi', handle: '@marta_food', bio: 'Authentic Italian recipes at home', location: 'Naples, Italy', platform: 'instagram', followers: 310000, engagement: 5.2, creatorSize: 'mid', niche: ['Food'], socialAccounts: { instagram: { handle: '@marta_food', followers: 310000 }, youtube: null, twitter: null }, pastCollaborations: 32, rating: 4.9 },
    { id: 'inf-066', name: 'Abebe Bikila', handle: '@abebe_run', bio: 'Marathon training & Ethiopian views', location: 'Addis Ababa, Ethiopia', platform: 'instagram', followers: 52000, engagement: 5.8, creatorSize: 'micro', niche: ['Sports'], socialAccounts: { instagram: { handle: '@abebe_run', followers: 52000 }, youtube: null, twitter: null }, pastCollaborations: 10, rating: 4.6 },
    { id: 'inf-067', name: 'Sven Larsson', handle: '@sven_design', bio: 'Nordic minimalist furniture design', location: 'Stockholm, Sweden', platform: 'instagram', followers: 125000, engagement: 6.1, creatorSize: 'mid', niche: ['Lifestyle'], socialAccounts: { instagram: { handle: '@sven_design', followers: 125000 }, youtube: null, twitter: null }, pastCollaborations: 18, rating: 4.8 },
];

// ─────────────────────────────────────────────────────────────
// Campaign–Influencer Relationships (lifecycle tracking)
// ─────────────────────────────────────────────────────────────

export const MOCK_CAMPAIGN_INFLUENCERS: CampaignInfluencer[] = [
    // Camp-001: Priya (invited, paid, script review stage)
    {
        id: 'ci-001',
        campaignId: 'camp-001',
        influencerId: 'inf-001',
        origin: 'brand_invite',
        status: 'script_review',
        chatEnabled: true,
        tierRate: 15000,
        negotiations: [
            { id: 'neg-001a', party: 'brand', amount: 15000, timestamp: '2026-02-11T10:00:00Z' },
            { id: 'neg-001b', party: 'influencer', amount: 22000, timestamp: '2026-02-11T14:00:00Z' },
            { id: 'neg-001c', party: 'brand', amount: 18000, timestamp: '2026-02-12T09:00:00Z' },
        ],
        agreedBudget: 18000,
        platformFee: 1800,
        firstPayment: 9900,
        finalPayment: 9900,
        paymentStatus: 'first_paid',
        scriptVersions: [
            { id: 'sv-001', version: 1, fileUrl: '#', fileName: 'script_v1.pdf', status: 'rejected', submittedAt: '2026-02-18T10:00:00Z', reviewedAt: '2026-02-19T09:00:00Z', reviewNote: 'Need more detail on product benefits' },
            { id: 'sv-002', version: 2, fileUrl: '#', fileName: 'script_v2.pdf', status: 'pending', submittedAt: '2026-02-20T14:00:00Z' },
        ],
        workSubmissions: [],
        connectedAt: '2026-02-11T10:00:00Z',
        acceptedAt: '2026-02-12T12:00:00Z',
        paidAt: '2026-02-12T15:00:00Z',
    },
    // Camp-001: Kavya (applied, paid, work pending)
    {
        id: 'ci-002',
        campaignId: 'camp-001',
        influencerId: 'inf-005',
        origin: 'influencer_application',
        status: 'work_pending',
        chatEnabled: true,
        tierRate: 8000,
        negotiations: [],
        agreedBudget: 8000,
        platformFee: 800,
        firstPayment: 4400,
        finalPayment: 4400,
        paymentStatus: 'first_paid',
        scriptVersions: [
            { id: 'sv-003', version: 1, fileUrl: '#', fileName: 'kavya_script.pdf', status: 'approved', submittedAt: '2026-02-16T10:00:00Z', reviewedAt: '2026-02-17T09:00:00Z' },
        ],
        workSubmissions: [],
        connectedAt: '2026-02-13T08:00:00Z',
        acceptedAt: '2026-02-14T10:00:00Z',
        paidAt: '2026-02-14T12:00:00Z',
    },
    // Camp-002: Arjun (applied, work review)
    {
        id: 'ci-003',
        campaignId: 'camp-002',
        influencerId: 'inf-002',
        origin: 'influencer_application',
        status: 'work_review',
        chatEnabled: true,
        tierRate: 5000,
        negotiations: [],
        agreedBudget: 5000,
        platformFee: 500,
        firstPayment: 2750,
        finalPayment: 2750,
        paymentStatus: 'first_paid',
        scriptVersions: [
            { id: 'sv-004', version: 1, fileUrl: '#', fileName: 'meme_concept.pdf', status: 'approved', submittedAt: '2026-02-15T14:00:00Z', reviewedAt: '2026-02-16T09:00:00Z' },
        ],
        workSubmissions: [
            { id: 'ws-001', type: 'file', url: '#', fileName: 'meme_final.jpg', status: 'pending', submittedAt: '2026-02-22T16:00:00Z' },
        ],
        connectedAt: '2026-02-06T12:00:00Z',
        acceptedAt: '2026-02-07T10:00:00Z',
        paidAt: '2026-02-07T12:00:00Z',
    },
    // Camp-004: Sneha (invited, payment pending)
    {
        id: 'ci-004',
        campaignId: 'camp-004',
        influencerId: 'inf-003',
        origin: 'brand_invite',
        status: 'payment_pending',
        chatEnabled: false,
        tierRate: 0,
        negotiations: [
            { id: 'neg-004a', party: 'influencer', amount: 5000, timestamp: '2026-02-18T15:00:00Z' },
        ],
        agreedBudget: null,
        platformFee: 0,
        firstPayment: 0,
        finalPayment: 0,
        paymentStatus: 'pending_first',
        scriptVersions: [],
        workSubmissions: [],
        connectedAt: '2026-02-17T09:00:00Z',
    },
    // Camp-004: Vikram (applied, accepted, script pending)
    {
        id: 'ci-005',
        campaignId: 'camp-004',
        influencerId: 'inf-006',
        origin: 'influencer_application',
        status: 'script_pending',
        chatEnabled: true,
        tierRate: 0,
        negotiations: [],
        agreedBudget: 0,
        platformFee: 0,
        firstPayment: 0,
        finalPayment: 0,
        paymentStatus: 'first_paid',
        scriptVersions: [],
        workSubmissions: [],
        connectedAt: '2026-02-16T08:00:00Z',
        acceptedAt: '2026-02-17T10:00:00Z',
        paidAt: '2026-02-17T10:00:00Z',
    },
    // Camp-005: Kavya (completed)
    {
        id: 'ci-006',
        campaignId: 'camp-005',
        influencerId: 'inf-005',
        origin: 'influencer_application',
        status: 'completed',
        chatEnabled: false,
        tierRate: 20000,
        negotiations: [],
        agreedBudget: 20000,
        platformFee: 2000,
        firstPayment: 11000,
        finalPayment: 11000,
        paymentStatus: 'completed',
        scriptVersions: [
            { id: 'sv-005', version: 1, fileUrl: '#', fileName: 'food_script.pdf', status: 'approved', submittedAt: '2026-01-20T10:00:00Z', reviewedAt: '2026-01-21T09:00:00Z' },
        ],
        workSubmissions: [
            { id: 'ws-002', type: 'link', url: 'https://instagram.com/p/example', proofOfWorkUrl: 'https://instagram.com/p/example', status: 'approved', submittedAt: '2026-02-01T12:00:00Z', reviewedAt: '2026-02-02T09:00:00Z' },
        ],
        connectedAt: '2026-01-12T08:00:00Z',
        acceptedAt: '2026-01-13T10:00:00Z',
        paidAt: '2026-01-13T12:00:00Z',
        completedAt: '2026-02-05T10:00:00Z',
    },
    // More applications for camp-001 for demonstration
    {
        id: 'ci-007',
        campaignId: 'camp-001',
        influencerId: 'inf-007',
        origin: 'influencer_application',
        status: 'applied',
        chatEnabled: false,
        tierRate: 8000,
        negotiations: [],
        agreedBudget: null,
        platformFee: 0,
        firstPayment: 0,
        finalPayment: 0,
        paymentStatus: 'pending_first',
        scriptVersions: [],
        workSubmissions: [],
        connectedAt: '2026-02-14T08:00:00Z',
    },
    {
        id: 'ci-008',
        campaignId: 'camp-001',
        influencerId: 'inf-008',
        origin: 'influencer_application',
        status: 'applied',
        chatEnabled: false,
        tierRate: 15000,
        negotiations: [],
        agreedBudget: null,
        platformFee: 0,
        firstPayment: 0,
        finalPayment: 0,
        paymentStatus: 'pending_first',
        scriptVersions: [],
        workSubmissions: [],
        connectedAt: '2026-02-14T09:00:00Z',
    },
    {
        id: 'ci-009',
        campaignId: 'camp-001',
        influencerId: 'inf-009',
        origin: 'influencer_application',
        status: 'applied',
        chatEnabled: false,
        tierRate: 8000,
        negotiations: [],
        agreedBudget: null,
        platformFee: 0,
        firstPayment: 0,
        finalPayment: 0,
        paymentStatus: 'pending_first',
        scriptVersions: [],
        workSubmissions: [],
        connectedAt: '2026-02-14T10:00:00Z',
    },
    {
        id: 'ci-010',
        campaignId: 'camp-001',
        influencerId: 'inf-010',
        origin: 'influencer_application',
        status: 'applied',
        chatEnabled: false,
        tierRate: 8000,
        negotiations: [],
        agreedBudget: null,
        platformFee: 0,
        firstPayment: 0,
        finalPayment: 0,
        paymentStatus: 'pending_first',
        scriptVersions: [],
        workSubmissions: [],
        connectedAt: '2026-02-14T11:00:00Z',
    },
    {
        id: 'ci-011',
        campaignId: 'camp-001',
        influencerId: 'inf-011',
        origin: 'influencer_application',
        status: 'applied',
        chatEnabled: false,
        tierRate: 8000,
        negotiations: [],
        agreedBudget: null,
        platformFee: 0,
        firstPayment: 0,
        finalPayment: 0,
        paymentStatus: 'pending_first',
        scriptVersions: [],
        workSubmissions: [],
        connectedAt: '2026-02-14T12:00:00Z',
    },
    {
        id: 'ci-012',
        campaignId: 'camp-001',
        influencerId: 'inf-012',
        origin: 'influencer_application',
        status: 'applied',
        chatEnabled: false,
        tierRate: 3000,
        negotiations: [],
        agreedBudget: null,
        platformFee: 0,
        firstPayment: 0,
        finalPayment: 0,
        paymentStatus: 'pending_first',
        scriptVersions: [],
        workSubmissions: [],
        connectedAt: '2026-02-14T13:00:00Z',
    },
    {
        id: 'ci-013',
        campaignId: 'camp-001',
        influencerId: 'inf-013',
        origin: 'influencer_application',
        status: 'applied',
        chatEnabled: false,
        tierRate: 8000,
        negotiations: [],
        agreedBudget: null,
        platformFee: 0,
        firstPayment: 0,
        finalPayment: 0,
        paymentStatus: 'pending_first',
        scriptVersions: [],
        workSubmissions: [],
        connectedAt: '2026-02-14T14:00:00Z',
    },
    {
        id: 'ci-014',
        campaignId: 'camp-001',
        influencerId: 'inf-014',
        origin: 'influencer_application',
        status: 'applied',
        chatEnabled: false,
        tierRate: 15000,
        negotiations: [],
        agreedBudget: null,
        platformFee: 0,
        firstPayment: 0,
        finalPayment: 0,
        paymentStatus: 'pending_first',
        scriptVersions: [],
        workSubmissions: [],
        connectedAt: '2026-02-14T15:00:00Z',
    },
    {
        id: 'ci-015',
        campaignId: 'camp-001',
        influencerId: 'inf-015',
        origin: 'influencer_application',
        status: 'applied',
        chatEnabled: false,
        tierRate: 8000,
        negotiations: [],
        agreedBudget: null,
        platformFee: 0,
        firstPayment: 0,
        finalPayment: 0,
        paymentStatus: 'pending_first',
        scriptVersions: [],
        workSubmissions: [],
        connectedAt: '2026-02-14T16:00:00Z',
    },
    {
        id: 'ci-016',
        campaignId: 'camp-001',
        influencerId: 'inf-016',
        origin: 'influencer_application',
        status: 'applied',
        chatEnabled: false,
        tierRate: 15000,
        negotiations: [],
        agreedBudget: null,
        platformFee: 0,
        firstPayment: 0,
        finalPayment: 0,
        paymentStatus: 'pending_first',
        scriptVersions: [],
        workSubmissions: [],
        connectedAt: '2026-02-14T17:00:00Z',
    },
    { id: 'ci-017', campaignId: 'camp-001', influencerId: 'inf-017', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 8000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-15T08:00:00Z' },
    { id: 'ci-018', campaignId: 'camp-001', influencerId: 'inf-018', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-15T09:00:00Z' },
    { id: 'ci-019', campaignId: 'camp-001', influencerId: 'inf-019', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 25000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-15T10:00:00Z' },
    { id: 'ci-020', campaignId: 'camp-001', influencerId: 'inf-020', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 20000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-15T11:00:00Z' },
    { id: 'ci-021', campaignId: 'camp-001', influencerId: 'inf-021', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 8000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-15T12:00:00Z' },
    { id: 'ci-022', campaignId: 'camp-001', influencerId: 'inf-022', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 5000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-15T13:00:00Z' },
    { id: 'ci-023', campaignId: 'camp-001', influencerId: 'inf-023', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-15T14:00:00Z' },
    { id: 'ci-024', campaignId: 'camp-001', influencerId: 'inf-024', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 12000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-15T15:00:00Z' },
    { id: 'ci-025', campaignId: 'camp-001', influencerId: 'inf-025', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 8000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-15T16:00:00Z' },
    { id: 'ci-026', campaignId: 'camp-001', influencerId: 'inf-026', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-15T17:00:00Z' },
    { id: 'ci-027', campaignId: 'camp-001', influencerId: 'inf-027', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 20000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-16T08:00:00Z' },
    { id: 'ci-028', campaignId: 'camp-001', influencerId: 'inf-028', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 8000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-16T09:00:00Z' },
    { id: 'ci-029', campaignId: 'camp-001', influencerId: 'inf-029', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-16T10:00:00Z' },
    { id: 'ci-030', campaignId: 'camp-001', influencerId: 'inf-030', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 30000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-16T11:00:00Z' },
    { id: 'ci-031', campaignId: 'camp-001', influencerId: 'inf-031', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 8000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-16T12:00:00Z' },
    { id: 'ci-032', campaignId: 'camp-001', influencerId: 'inf-032', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-16T13:00:00Z' },
    { id: 'ci-033', campaignId: 'camp-001', influencerId: 'inf-033', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 18000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-16T14:00:00Z' },
    { id: 'ci-034', campaignId: 'camp-001', influencerId: 'inf-034', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 8000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-16T15:00:00Z' },
    { id: 'ci-035', campaignId: 'camp-001', influencerId: 'inf-035', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-16T16:00:00Z' },
    { id: 'ci-036', campaignId: 'camp-001', influencerId: 'inf-036', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 8000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-16T17:00:00Z' },
    { id: 'ci-037', campaignId: 'camp-001', influencerId: 'inf-037', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-17T08:00:00Z' },
    { id: 'ci-038', campaignId: 'camp-001', influencerId: 'inf-038', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 25000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-17T09:00:00Z' },
    { id: 'ci-039', campaignId: 'camp-001', influencerId: 'inf-039', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 8000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-17T10:00:00Z' },
    { id: 'ci-040', campaignId: 'camp-001', influencerId: 'inf-040', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 12000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-17T11:00:00Z' },
    { id: 'ci-041', campaignId: 'camp-001', influencerId: 'inf-041', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-17T12:00:00Z' },
    { id: 'ci-042', campaignId: 'camp-001', influencerId: 'inf-042', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 18000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-17T13:00:00Z' },
    { id: 'ci-043', campaignId: 'camp-001', influencerId: 'inf-043', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 20000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-17T14:00:00Z' },
    { id: 'ci-044', campaignId: 'camp-001', influencerId: 'inf-044', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 8000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-17T15:00:00Z' },
    { id: 'ci-045', campaignId: 'camp-001', influencerId: 'inf-045', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-17T16:00:00Z' },
    { id: 'ci-046', campaignId: 'camp-001', influencerId: 'inf-046', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 18000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-17T17:00:00Z' },
    { id: 'ci-047', campaignId: 'camp-001', influencerId: 'inf-047', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-18T08:00:00Z' },
    { id: 'ci-048', campaignId: 'camp-001', influencerId: 'inf-048', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 8000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-18T09:00:00Z' },
    { id: 'ci-049', campaignId: 'camp-001', influencerId: 'inf-049', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-18T10:00:00Z' },
    { id: 'ci-050', campaignId: 'camp-001', influencerId: 'inf-050', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 12000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-18T11:00:00Z' },
    { id: 'ci-051', campaignId: 'camp-001', influencerId: 'inf-051', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 20000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-18T12:00:00Z' },
    { id: 'ci-052', campaignId: 'camp-001', influencerId: 'inf-052', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 8000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-18T13:00:00Z' },
    { id: 'ci-053', campaignId: 'camp-001', influencerId: 'inf-053', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-18T14:00:00Z' },
    { id: 'ci-054', campaignId: 'camp-001', influencerId: 'inf-054', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 6000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-18T15:00:00Z' },
    { id: 'ci-055', campaignId: 'camp-001', influencerId: 'inf-055', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 18000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-18T16:00:00Z' },
    { id: 'ci-056', campaignId: 'camp-001', influencerId: 'inf-056', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-18T17:00:00Z' },
    { id: 'ci-057', campaignId: 'camp-001', influencerId: 'inf-057', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 5000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-19T08:00:00Z' },
    { id: 'ci-058', campaignId: 'camp-001', influencerId: 'inf-058', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-19T09:00:00Z' },
    { id: 'ci-059', campaignId: 'camp-001', influencerId: 'inf-059', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 35000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-19T10:00:00Z' },
    { id: 'ci-060', campaignId: 'camp-001', influencerId: 'inf-060', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 8000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-19T11:00:00Z' },
    { id: 'ci-061', campaignId: 'camp-001', influencerId: 'inf-061', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-19T12:00:00Z' },
    { id: 'ci-062', campaignId: 'camp-001', influencerId: 'inf-062', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 18000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-19T13:00:00Z' },
    { id: 'ci-063', campaignId: 'camp-001', influencerId: 'inf-063', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 8000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-19T14:00:00Z' },
    { id: 'ci-064', campaignId: 'camp-001', influencerId: 'inf-064', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-19T15:00:00Z' },
    { id: 'ci-065', campaignId: 'camp-001', influencerId: 'inf-065', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 18000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-19T16:00:00Z' },
    { id: 'ci-066', campaignId: 'camp-001', influencerId: 'inf-066', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 8000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-19T17:00:00Z' },
    { id: 'ci-067', campaignId: 'camp-001', influencerId: 'inf-067', origin: 'influencer_application', status: 'applied', chatEnabled: false, tierRate: 15000, negotiations: [], agreedBudget: null, platformFee: 0, firstPayment: 0, finalPayment: 0, paymentStatus: 'pending_first', scriptVersions: [], workSubmissions: [], connectedAt: '2026-02-20T08:00:00Z' },
];

// ─────────────────────────────────────────────────────────────
// Applications (legacy — to be replaced by MOCK_CAMPAIGN_INFLUENCERS)
// ─────────────────────────────────────────────────────────────

export const MOCK_APPLICATIONS = [
    { id: 'app-001', influencer: MOCK_INFLUENCERS[0], campaignId: 'camp-001', status: 'pending' as const, appliedAt: '2026-02-12T14:30:00Z', message: 'Would love to create content for your skincare launch! I have experience with similar brands.' },
    { id: 'app-002', influencer: MOCK_INFLUENCERS[4], campaignId: 'camp-001', status: 'accepted' as const, appliedAt: '2026-02-11T10:00:00Z', message: 'My audience loves skincare products. Excited to collaborate!' },
    { id: 'app-003', influencer: MOCK_INFLUENCERS[5], campaignId: 'camp-004', status: 'pending' as const, appliedAt: '2026-02-16T08:00:00Z', message: 'I create authentic unboxing content. Let me showcase your gadgets!' },
    { id: 'app-004', influencer: MOCK_INFLUENCERS[1], campaignId: 'camp-002', status: 'accepted' as const, appliedAt: '2026-02-06T12:00:00Z', message: 'Ready to create viral memes for your campaign!' },
    { id: 'app-005', influencer: MOCK_INFLUENCERS[2], campaignId: 'camp-004', status: 'pending' as const, appliedAt: '2026-02-17T09:00:00Z', message: 'Tech reviews are my forte. Would love to review your products.' },
];

export const MOCK_SCRIPTS = [
    { id: 'scr-001', influencer: MOCK_INFLUENCERS[4], campaignId: 'camp-001', status: 'pending' as const, submittedAt: '2026-02-18T10:00:00Z', content: 'Opening shot: Natural morning light, me at my vanity. "I have been trying this new skincare range for 2 weeks and honestly..." [continue with authentic review]', revisionNotes: null },
    { id: 'scr-002', influencer: MOCK_INFLUENCERS[1], campaignId: 'camp-002', status: 'approved' as const, submittedAt: '2026-02-15T14:00:00Z', content: 'Meme format: Drake template — "Spending money wisely" vs "Breaking the internet with [Brand]". Follow-up carousel with 5 variations.', revisionNotes: null },
    { id: 'scr-003', influencer: MOCK_INFLUENCERS[2], campaignId: 'camp-004', status: 'revision' as const, submittedAt: '2026-02-20T11:00:00Z', content: 'YouTube video: 8-min detailed unboxing and first impressions. Chapters: Packaging, Design, Features, Performance, Verdict.', revisionNotes: 'Please add a comparison section with competitor products.' },
];

export const MOCK_SUBMISSIONS = [
    { id: 'sub-001', influencer: MOCK_INFLUENCERS[1], campaignId: 'camp-002', status: 'pending' as const, submittedAt: '2026-02-22T16:00:00Z', mediaType: 'image' as const, mediaUrl: undefined, caption: 'When your bestie says they found a better brand... #BreakTheInternet', likes: 0, comments: 0 },
    { id: 'sub-002', influencer: MOCK_INFLUENCERS[4], campaignId: 'camp-001', status: 'approved' as const, submittedAt: '2026-02-20T12:00:00Z', mediaType: 'video' as const, mediaUrl: undefined, caption: '2 weeks with Summer Glow and my skin has never looked better ✨', likes: 4200, comments: 180 },
];

export const MOCK_NEGOTIATIONS = [
    { id: 'neg-001', influencer: MOCK_INFLUENCERS[0], campaignId: 'camp-001', status: 'pending' as const, originalBudget: 15000, proposedBudget: 22000, message: 'Given my audience size and engagement, I believe ₹22,000 would be fair for this campaign.', createdAt: '2026-02-13T10:00:00Z' },
    { id: 'neg-002', influencer: MOCK_INFLUENCERS[2], campaignId: 'camp-004', status: 'countered' as const, originalBudget: 0, proposedBudget: 5000, message: 'I would prefer a small payment along with the product for my review.', counterOffer: 3000, createdAt: '2026-02-18T15:00:00Z' },
];

export const MOCK_ACTIVITY_FEED = [
    { id: 'act-001', type: 'application' as const, message: 'Priya Sharma applied to Summer Glow Skincare Launch', timestamp: '2026-02-25T14:30:00Z', campaignId: 'camp-001' },
    { id: 'act-002', type: 'script' as const, message: 'Kavya Nair submitted a script for Summer Glow Skincare Launch', timestamp: '2026-02-25T12:00:00Z', campaignId: 'camp-001' },
    { id: 'act-003', type: 'submission' as const, message: 'Arjun Kapoor submitted content for Viral Meme Challenge', timestamp: '2026-02-25T10:00:00Z', campaignId: 'camp-002' },
    { id: 'act-004', type: 'negotiation' as const, message: 'Sneha Reddy initiated a negotiation on UGC Product Unboxing', timestamp: '2026-02-25T08:00:00Z', campaignId: 'camp-004' },
    { id: 'act-005', type: 'payment' as const, message: 'Payment confirmed for Food Review Series campaign', timestamp: '2026-02-24T18:00:00Z', campaignId: 'camp-005' },
    { id: 'act-006', type: 'application' as const, message: 'Vikram Singh applied to UGC Product Unboxing', timestamp: '2026-02-24T16:00:00Z', campaignId: 'camp-004' },
];

export const MOCK_NOTIFICATIONS = [
    { id: 'notif-001', type: 'application' as const, title: 'New Application', message: 'Priya Sharma applied to your campaign "Summer Glow Skincare Launch"', campaignId: 'camp-001', campaignName: 'Summer Glow Skincare Launch', influencerId: 'inf-001', influencerName: 'Priya Sharma', isRead: false, createdAt: '2026-02-25T14:30:00Z' },
    { id: 'notif-002', type: 'script' as const, title: 'Script Submitted', message: 'Kavya Nair submitted a script for review', campaignId: 'camp-001', campaignName: 'Summer Glow Skincare Launch', influencerId: 'inf-005', influencerName: 'Kavya Nair', isRead: false, createdAt: '2026-02-25T12:00:00Z' },
    { id: 'notif-003', type: 'submission' as const, title: 'Content Submitted', message: 'Arjun Kapoor submitted final content for Viral Meme Challenge', campaignId: 'camp-002', campaignName: 'Viral Meme Challenge', influencerId: 'inf-002', influencerName: 'Arjun Kapoor', isRead: true, createdAt: '2026-02-25T10:00:00Z' },
    { id: 'notif-004', type: 'negotiation' as const, title: 'Negotiation Request', message: 'Sneha Reddy wants to negotiate budget for UGC Product Unboxing', campaignId: 'camp-004', campaignName: 'UGC Product Unboxing', influencerId: 'inf-003', influencerName: 'Sneha Reddy', isRead: false, createdAt: '2026-02-25T08:00:00Z' },
    { id: 'notif-005', type: 'system' as const, title: 'Campaign Completed', message: 'Food Review Series campaign has been completed successfully', campaignId: 'camp-005', campaignName: 'Food Review Series', isRead: true, createdAt: '2026-02-24T18:00:00Z' },
];

export const MOCK_MESSAGES = [
    {
        id: 'conv-001',
        campaignId: 'camp-001',
        influencer: { id: 'inf-005', name: MOCK_INFLUENCERS[4].name, handle: MOCK_INFLUENCERS[4].handle },
        campaignName: 'Summer Glow Skincare Launch',
        status: 'active' as const,
        lastMessage: 'Sure, I\'ll update the script and send it by tomorrow!',
        lastMessageAt: '2026-02-25T13:00:00Z',
        unread: 2,
        messages: [
            { id: 'msg-001', sender: 'brand' as const, content: 'Hi Kavya! Welcome to the campaign. Excited to work with you.', timestamp: '2026-02-18T10:00:00Z' },
            { id: 'msg-002', sender: 'influencer' as const, content: 'Thank you! I\'m excited too. When should I submit the script?', timestamp: '2026-02-18T10:05:00Z' },
            { id: 'msg-003', sender: 'brand' as const, content: 'Please submit by Feb 25. Also, can you include a before/after segment?', timestamp: '2026-02-18T10:10:00Z' },
            { id: 'msg-004', sender: 'influencer' as const, content: 'Sure, I\'ll update the script and send it by tomorrow!', timestamp: '2026-02-25T13:00:00Z' },
        ],
    },
    {
        id: 'conv-002',
        campaignId: 'camp-002',
        influencer: { id: 'inf-002', name: MOCK_INFLUENCERS[1].name, handle: MOCK_INFLUENCERS[1].handle },
        campaignName: 'Viral Meme Challenge',
        status: 'active' as const,
        lastMessage: 'Submitted the final meme set. Check it out!',
        lastMessageAt: '2026-02-25T10:00:00Z',
        unread: 0,
        messages: [
            { id: 'msg-005', sender: 'brand' as const, content: 'Hey Arjun! The meme format looks great. Go ahead with production.', timestamp: '2026-02-16T09:00:00Z' },
            { id: 'msg-006', sender: 'influencer' as const, content: 'Submitted the final meme set. Check it out!', timestamp: '2026-02-25T10:00:00Z' },
        ],
    },
    {
        id: 'conv-003',
        campaignId: 'camp-005',
        influencer: { id: 'inf-005', name: MOCK_INFLUENCERS[4].name, handle: MOCK_INFLUENCERS[4].handle },
        campaignName: 'Food Review Series',
        status: 'archived' as const,
        lastMessage: 'Great working with you! Campaign completed.',
        lastMessageAt: '2026-02-05T10:00:00Z',
        unread: 0,
        messages: [
            { id: 'msg-007', sender: 'brand' as const, content: 'Great working with you! Campaign completed.', timestamp: '2026-02-05T10:00:00Z' },
        ],
    },
];

export const MOCK_ANALYTICS = {
    overview: {
        totalReach: 2450000,
        totalEngagement: 185000,
        roi: 3.2,
        contentPieces: 48,
        totalSpend: 440000,
        activeCampaigns: 3,
    },
    monthlyTrends: [
        { month: 'Sep', reach: 180000, engagement: 12000, spend: 45000 },
        { month: 'Oct', reach: 220000, engagement: 18000, spend: 55000 },
        { month: 'Nov', reach: 310000, engagement: 28000, spend: 72000 },
        { month: 'Dec', reach: 450000, engagement: 35000, spend: 80000 },
        { month: 'Jan', reach: 520000, engagement: 42000, spend: 88000 },
        { month: 'Feb', reach: 770000, engagement: 50000, spend: 100000 },
    ],
    campaignTypeBreakdown: [
        { type: 'Influencer Marketing', value: 40, color: '#0a0a0a' },
        { type: 'UGC Marketing', value: 28, color: '#fedc03' },
        { type: 'Meme Marketing', value: 20, color: '#6b7280' },
        { type: 'Twitter Marketing', value: 12, color: '#d1d5db' },
    ],
    topCampaigns: [
        { name: 'Summer Glow Skincare Launch', reach: 850000, engagement: 4.2, roi: 4.1 },
        { name: 'Viral Meme Challenge', reach: 620000, engagement: 6.8, roi: 3.8 },
        { name: 'Food Review Series', reach: 380000, engagement: 5.1, roi: 2.9 },
    ],
};

export type Campaign = typeof MOCK_CAMPAIGNS[number];
export type Influencer = typeof MOCK_INFLUENCERS[number];
export type Application = typeof MOCK_APPLICATIONS[number];
export type Script = typeof MOCK_SCRIPTS[number];
export type Submission = typeof MOCK_SUBMISSIONS[number];
export type Negotiation = typeof MOCK_NEGOTIATIONS[number];
